FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

# --- Make ubuntu behave as root ---
RUN usermod -o -u 0 -g 0 ubuntu \
  && mkdir -p /home/ubuntu \
  && chown -R 0:0 /home/ubuntu

# --- System packages ---
RUN apt-get update && apt-get install -y \
    curl \
    git \
    jq \
    ripgrep \
    build-essential \
    python3-pip \
    python3-venv \
    unzip \
    locales \
    fd-find \
  && rm -rf /var/lib/apt/lists/*

# --- HDF5 tools ---
RUN apt-get update && apt-get install -y \
    hdf5-tools \
  && rm -rf /var/lib/apt/lists/*

# --- Java ---
RUN apt-get update && apt-get install -y \
    maven \
    default-jdk \
  && rm -rf /var/lib/apt/lists/*

# --- Node.js ---
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
  && apt-get install -y nodejs \
  && rm -rf /var/lib/apt/lists/*

# --- pi ---
RUN npm install -g @earendil-works/pi-coding-agent@0.79.3

ENV EDITOR=nvim

RUN mkdir -p /home/ubuntu/.pi

# --- nvim ---
RUN curl -fLO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz \
  && tar -C /opt -xzf nvim-linux-x86_64.tar.gz \
  && rm nvim-linux-x86_64.tar.gz

ENV PATH="${PATH}:/opt/nvim-linux-x86_64/bin"

# --- UV ---
RUN su -c 'curl -LsSf https://astral.sh/uv/install.sh | sh' ubuntu

ENV PATH="${PATH}:/home/ubuntu/.local/bin"

# --- Do the rest ---
ENV HOME=/home/ubuntu

COPY --chmod=0755 scripts/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

USER ubuntu

ENTRYPOINT ["docker-entrypoint.sh"]
